fluent/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^submit/', include('submit.urls', namespace='submit')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

submit/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.submitTask, name='submitTask'),
    url(r'^submitCasDat/$', views.submitCasDat, name='submitCasDat'),
    url(r'^setPara/$', views.setPara, name='setPara'),
]

submit/models.py
from django.db import models
from django.forms import ModelForm
from django import forms


# Create your models here.
class ComIns(models.Model):
    title = models.CharField(max_length=60)
    cas = models.FileField(upload_to='')
    dat = models.FileField(upload_to='')

    def __str__(self):
        return self.title


class ComInsForm(ModelForm):
    class Meta:
        model = ComIns
        fields = '__all__'


class SubmitForm(forms.Form):
    taskname = forms.CharField()
    casfile = forms.FileField()
    datfile = forms.FileField()

submit/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import SubmitForm, ComIns
import paramiko, time


# Create your views here.
def submitTask(request):
    return render(request, 'submit/submit.html')


def submitCasDat(request):
    if request.method == 'POST':
        formContext = SubmitForm(request.POST, request.FILES)
        if formContext.is_valid():
            # acquire data
            task_title = formContext.cleaned_data['taskname']
            task_cas = formContext.cleaned_data['casfile']
            task_dat = formContext.cleaned_data['datfile']

            # import to database
            task = ComIns()
            task.title = task_title
            task.cas = task_cas
            task.dat = task_dat
            task.save()

            # write .jou file
            p = ComIns.objects.get(title=task_title)

            with open('/home/tiger/Projects/Django/Fluent/media/test.jou', 'w') as f:
                f.write('/file/read-case-data\n')
                casAddress = task_title + '.cas'
                casAddress = '/home/lion/Tiger/Fluent/' + casAddress + '\n'
                f.write(casAddress)
                f.write('\n')

            return render(request, 'submit/set_para.html')
    else:
        formContext = SubmitForm()
    return HttpResponse('upload fail')


def setPara(request):
    if request.method == 'POST':
        num = str(request.POST['iterateNum'])
        with open('/home/tiger/Projects/Django/Fluent/media/test.jou', 'r') as f:
            filename = f.readlines()
            filename = filename[1].split('/')[-1]
            filename = filename.split('.')[0]

        with open('/home/tiger/Projects/Django/Fluent/media/test.jou', 'a') as f:
            f.write('/solve/iterate\n')
            f.write(num + '\n')
            f.write('\n')
            f.write('/file/write-case-data\n')
            f.write('/home/lion/Tiger/Fluent/' + filename + '-' + num + '.cas\n')
            f.write('\n')
            f.write('/exit')

        with open('/home/tiger/Projects/Django/Fluent/media/test.sh','w') as f:
            f.write('#!/bin/bash\n')
            f.write('fluent 2d -g -i /home/lion/Tiger/Fluent/test.jou')

        # SSH
        host = "10.0.0.17"
        port = 22
        transport = paramiko.Transport((host, port))

        password = "airation"
        username = "lion"
        transport.connect(username=username, password=password)

        sftp = paramiko.SFTPClient.from_transport(transport)

        filepath = '/home/lion/Tiger/Fluent/test.cas'
        localpath = '/home/tiger/Projects/Django/Fluent/media/test.cas'
        sftp.put(localpath, filepath)

        filepath = '/home/lion/Tiger/Fluent/test.dat'
        localpath = '/home/tiger/Projects/Django/Fluent/media/test.dat'
        sftp.put(localpath, filepath)

        filepath = '/home/lion/Tiger/Fluent/test.jou'
        localpath = '/home/tiger/Projects/Django/Fluent/media/test.jou'
        sftp.put(localpath, filepath)

        filepath = '/home/lion/Tiger/Fluent/test.sh'
        localpath = '/home/tiger/Projects/Django/Fluent/media/test.sh'
        sftp.put(localpath, filepath)

        sftp.close()
        transport.close()

        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(host, 22, username=username, password=password)
        #ssh.exec_command("chmod +x /home/lion/Tiger/Fluent/test.sh")
        #ssh.exec_command("/home/lion/Tiger/Fluent/test.sh")
        #ssh.exec_command("fluent 2d -g -i /home/lion/Tiger/Fluent/test.jou")

        channel = ssh.invoke_shell()
        stdin = channel.makefile('wb')
        stdout = channel.makefile('rb')

        stdin.write('''
            chmod +x /home/lion/Tiger/Fluent/test.sh
            /home/lion/Tiger/Fluent/test.sh
        ''')
        time.sleep(5)

        stdout.close()
        stdin.close()

        ssh.close()

        return HttpResponse('task ok')
    else:
        return HttpResponse('task fail')

templates/submit/set_para.html
<html>
<head>
<div>
    <form action="{% url 'submit:setPara' %}" method="post">
    {% csrf_token %}
        Iteration:
        <input type="text" name="iterateNum" />
        <input type="submit" value="Submit" />
    </form>
</div>
</head>
</html>

templates/submit/submit.html
<!DOCTYPE html>
<html>
<head>
    <script src="/static/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="/static/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
<body>
  <div>
    <h1>Submit Your Task</h1>
    <hr>
    <div>
        <form action="{% url 'submit:submitCasDat' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>Your Task Name:</p>
            <input type="text" name="taskname" />
            <!--
            <input type="submit" name="conform" class="btn" value="conform"/>
            -->
            <hr>
            <p>Upload Your Case File</p>
            <input type='text' name='casname' id='casname' /> 
            <input type="file" name="casfile" class="file" id="fileField" size="28" onchange="document.getElementById('casname').value=this.value" />
            <!--
            <input type="submit" name="submit" class="btn" value="upload" />
            -->
            <hr>
            <p>Upload Your Data File</p>
            <input type='text' name='datname' id='datname' /> 
            <input type="file" name="datfile" class="file" id="fileField" size="28" onchange="document.getElementById('datname').value=this.value" />
            <!--
            <input type="submit" name="submit" class="btn" value="upload" />
            -->
            <hr>
            <input type='submit' value="Submit" />
        </form>
</body>
</html>